/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    
  Javascript: [{type: 'autogenerated', dirName: 'Javascript'}],   
  Java: [{type: 'autogenerated', dirName: 'Java'}],  
  Git: [{type: 'autogenerated', dirName: 'Git'}], 
  SQL: [{type: 'autogenerated', dirName: 'SQL'}], 
  HTML: [{type: 'autogenerated', dirName: 'HTML'}], 
  CSS: [{type: 'autogenerated', dirName: 'CSS'}], 
  React: [{type: 'autogenerated', dirName: 'React'}], 
  Node: [{type: 'autogenerated', dirName: 'Node'}], 
  Vuepress: [{type: 'autogenerated', dirName: 'Vuepress'}], 
  vue: [{type: 'autogenerated', dirName: 'vue'}], 
};

module.exports = sidebars;
